# Use postgres/example user/password credentials
version: "3.1"

services:
  app:
    build: .
    restart: always
    ports:
      - 5000:5000
    links:
      - db
    environment:
      - DATABASE_URL=dbname='postgres' user='postgres' host='db' password='root'

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
