{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart-deploy.serviceAccountName" . }}
  labels:
{{ include "chart-deploy.labels" . | nindent 4 }}
{{- end -}}
